question_data = [
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": '"Typewriter" is the longest word that can be typed using only the first row on a QWERTY keyboard.',
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The vapor produced by e-cigarettes is actually water.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The sum of all the numbers on a roulette wheel is 666.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Furby was released in 1998.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "There are 86400 seconds in a day.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The word &quot;news&quot; originates from the first letters of the 4 main directions on a "
                 "compass (North, East, West, South).",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "An eggplant is a vegetable.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The bikini is named after the &quot;Bikini Atoll&quot;, an island where "
                 "the United States conducted tests on atomic bombs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Cucumbers are usually more than 90% water.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The term &quot;Spam&quot; came before the food product &quot;Spam&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Kissing someone for one minute burns about 2 calories.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The French word to travel is &quot;Travail&quot;",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The French word for &quot;glass&quot; is &quot;glace&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": '"Santa Claus" is a variety of melon.',
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The scientific name for the Southern Lights is Aurora Australis?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Haggis is traditionally ate on Burns Night.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Francis Bacon died from a fatal case of pneumonia "
                 "while he was attempting to preserve meat by stuffing a chicken with snow.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA "
                 "where he sold the snack on the streets of Chicago.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The commercial UK channel ITV stands for &quot;International Television&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The pickled gherkin was first added to hamburgers"
                 " because a US health law required all fast-food to include a source of Vitamin C.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": '"Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo."'
                 ' is a grammatically correct sentence.',
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
